### ISSUE TITLE
from pycocotools.coco import COCO fails

### ISSUE THREAD

**Issue by Thrasi** [pdollar/coco#14]
After the update the tutorial doesn't run.

`$ git clone https://github.com/pdollar/coco.git
$ cd coco/PythonAPI
$ ipython
> from pycocotools.coco import COCO fails
...
> ImportError: No module named _mask`

**Comment by Thrasi** [comment]
my bad. forgot to make

**Comment by jgmatu** [comment]
Thanks the scrip you create must be place in PythonAPI/ and you have to make first.

**Comment by mememimis** [comment]
Hello, i am quite new, but can you write the exact steps that should be followed in order one to do make?

**Comment by kunimatsu-tri** [comment]
The steps below worked for me:

```
$ cd coco/PythonAPI
$ make
$ sudo make install
$ sudo python setup.py install
```

**Comment by Thrianadh** [comment]
It Runs 2.6 or 2.7 Only

python 2.6.x or 2.7.x (not python 3.x)
numpy 1.2.1 or later (the version must fit to the python version)
matplotlib 1.0.1 or later (the version must fit to the python version)

http://coco.lri.fr/COCOdoc/installation.html

**Comment by cardwing** [comment]
Add one more comment. If you use python 3, then you should change '$ sudo python setup.py install' to '$ sudo python3 setup.py install'.

**Comment by lihua213** [comment]
@cardwing Can you run it successfully with python 3?

**Comment by salihkaragoz** [comment]
@lihua213 Hello I installed, you can see at below

`sudo apt install python3-pip`
`pip3 install Cython`
`pip3 install numpy`

then i changed 'python' --> 'python3' in cocoapi/PythonAPI/Makefile 
you can check in [here](https://github.com/cocodataset/cocoapi/pull/128)
then run make under the PythonAPI

best

**Comment by brownpanther** [comment]
is there a way to make with a windows set up? I am using python 3.6

**Comment by tfoa** [comment]
@brownpanther hey we have same problem, im using windows and python 3.65 too, and still tryin yet, if u already solved it pls let me know too,

**Comment by jgmatu** [comment]
it is possible you need install some dependencies if the problem is on the import. I dont remember how I fix the issue but is possible this help you.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: tfoa <notifications@github.com> Date: 8/26/18  01:11  (GMT+01:00) To: cocodataset/cocoapi <cocoapi@noreply.github.com> Cc: Javi <fj.gutierrezs91@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [cocodataset/cocoapi] from pycocotools.coco import COCO fails (#14) 
@brownpanther hey we have same problem, im using windows and python 3.65 too, and still tryin yet, if u already solved it pls let me know too,

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cocodataset/cocoapi","title":"cocodataset/cocoapi","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/cocodataset/cocoapi"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tfoa in #14: @brownpanther hey we have same problem, im using windows and python 3.65 too, and still tryin yet, if u already solved it pls let me know too,"}],"action":{"name":"View Issue","url":"https://github.com/cocodataset/cocoapi/issues/14#issuecomment-416002278"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cocodataset/cocoapi/issues/14#issuecomment-416002278",
"url": "https://github.com/cocodataset/cocoapi/issues/14#issuecomment-416002278",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [cocodataset/cocoapi] from pycocotools.coco import COCO fails (#14)",
"sections": [
{
"text": "",
"activityTitle": "**tfoa**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@tfoa",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"cocodataset/cocoapi\",\n\"issueId\": 14,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/cocodataset/cocoapi/issues/14#issuecomment-416002278"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 139087740\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by brownpanther** [comment]
@tfoa I didn't end up using this architecture but I remember solving the issue. This is my comment from [this video](https://www.youtube.com/watch?v=2TikTv6PWDw&t=1s) I was following: 

Just want to say the issue is resolved - the problem was I didn't build coco correctly with 
pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI 
because my tensorflow dependencies were out of whack﻿

**Comment by tfoa** [comment]
actually i try install: python setup.py build_ext from(
https://github.com/epfml/sent2vec) and i founded command line error d8021L
invalid nurmeric argument '/Wno-cpp'
so i try install coco and thought it still cant fix it..but yet it isnt..so
do u think its installed on linux only ?cause windows still cant get it ?
[image: wnocpp1.JPG]
[image: wnocpp2.JPG]

Pada tanggal Sen, 27 Agt 2018 pukul 03.10 Nabila Abraham <
notifications@github.com> menulis:

**Comment by SoloyT** [comment]
Hi 
I installed it successfully. However, I couldnt "import pycocotools._mask" in different directory.
Please help! Thanks.

**Comment by Glomels** [comment]
> Hi
> I installed it successfully. However, I couldnt "import pycocotools._mask" in different directory.
> Please help! Thanks.

I'm having this problem too. Any luck resolving it?

**Comment by MitraTj** [comment]
Hi @Glomels I just uninstalled it completely and re-installed. then it works!
try and let us know

**Comment by vyviansomaya** [comment]
It still fails for me. these are the following steps I took

$ git clone https://github.com/pdollar/coco.git
$ cd coco/PythonAPI
$ make 
$python setup.py install 

I open a new notebook in AWS SageMaker in the PythonAPI directory and tried to import pycocotools, it succeeded.
Next, I tried "from pycocotools.coco import COCO" and got the "No module named _mask" output. I have done everything in the comments above and I still fail. The only difference I notice is that I'm using SageMaker . should that be the issue? or if its something else please let me know!

**Comment by Samjith888** [comment]
While run make on COCO\PythonAPI, got the following error
Unable to find vcvarsall.bat

Then i used the command "python setup.py build_ext --inplace" in the Makefile in the COCO\PythonAPI , Hence I'm getting the following error. How can i solve this issues and make it successfully

getting the following error 
![err](https://user-images.githubusercontent.com/39676803/54280617-e84ce600-45bd-11e9-8070-4b69e9fe5ed5.PNG)

**Comment by Samjith888** [comment]
> The steps below worked for me:
> 
> ```
> $ cd coco/PythonAPI
> $ make
> $ sudo make install
> $ sudo python setup.py install
> ```

Getting error: command 'cl.exe' failed: no such files or directory

**Comment by juhoward** [comment]
Try replacing extra_compile_args=['-Wno-cpp', '-Wno-unused-function', '-std=c99'] with extra_compile_args={'gcc': ['/Qstd=c99']} in coco/pycocotools/setup.py.

And then run python setup.py install again
*suggestion taken from https://github.com/cocodataset/cocoapi/issues/51
